FROM golang:1.7.5-alpine

WORKDIR /var/www/redis-lib/

RUN apk --no-cache add ca-certificates
RUN go get github.com/onsi/ginkgo/ginkgo
RUN go get github.com/onsi/gomega
RUN go get github.com/garyburd/redigo/redis
RUN go get github.com/rafaeljusto/redigomock

COPY . redis/
